---
- name: Remediate high CPU alert
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Show remediation action
      ansible.builtin.debug:
        msg: "Remediation triggered for localhost due to high cpu alert."